FROM mcr.microsoft.com/dotnet/core/runtime:2.1

WORKDIR /app
COPY . .
RUN apt-get update
RUN apt install ffmpeg -y
# Select non-root port
ENV ASPNETCORE_URLS=http://+:5000
# Do not run as root user
RUN chown -R www-data:www-data /app
USER www-data
HEALTHCHECK --interval=30s --timeout=10s CMD curl -f http://localhost:5000/api/health || exit 1
ENTRYPOINT ["dotnet", "API.dll"]
